import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const MOCK_ASSETS = [
  {
    platform_id: 'surplex',
    lot_id: 'SPX-MOCK-001',
    title: 'KUKA KR 210 R2700 Prime — Robot Industrial 6 Ejes',
    description: 'Robot KUKA KR 210 con controlador KRC4 y cable de 15m. Ideal para soldadura y manipulación de piezas pesadas. Mantenimiento completo al día.',
    category: 'Robótica Industrial',
    subcategory: 'Brazos Robot',
    source_url: 'https://www.surplex.com/es/l/robot-kuka-kr-210.html',
    current_bid: 18500,
    currency: 'EUR',
    estimated_resale: 42000,
    buyer_premium_pct: 16,
    has_reserve: true,
    starting_bid: 15000,
    city: 'Stuttgart',
    region: 'Baden-Württemberg',
    country: 'Alemania',
    country_code: 'DE',
    lat: 48.7758,
    lng: 9.1829,
    site_type: 'factory',
    auction_end: new Date(Date.now() + 3 * 86400000).toISOString(),
    inspection_available: true,
    make: 'KUKA',
    model: 'KR 210 R2700 Prime',
    year: 2018,
    condition: 'excellent' as const,
    hours: 8500,
    weight_kg: 1072,
    source: 'mock',
  },
  {
    platform_id: 'troostwijk',
    lot_id: 'TWK-MOCK-002',
    title: 'DMG Mori CMX 600 V — Centro de Mecanizado Vertical',
    description: 'Centro de mecanizado CMX 600 V con mesa 1300x600, husillo 10000rpm, herramienta 30 posiciones. Poco uso, en excelente estado.',
    category: 'Mecanizado CNC',
    subcategory: 'Centros de Mecanizado',
    source_url: 'https://www.troostwijkauctions.com/es/l/dmg-mori-cmx-600.html',
    current_bid: 28000,
    currency: 'EUR',
    estimated_resale: 55000,
    buyer_premium_pct: 18,
    has_reserve: false,
    starting_bid: 22000,
    city: 'Barcelona',
    region: 'Cataluña',
    country: 'España',
    country_code: 'ES',
    lat: 41.3851,
    lng: 2.1734,
    site_type: 'workshop',
    auction_end: new Date(Date.now() + 5 * 86400000).toISOString(),
    inspection_available: true,
    make: 'DMG Mori',
    model: 'CMX 600 V',
    year: 2020,
    condition: 'excellent' as const,
    hours: 3200,
    weight_kg: 6500,
    source: 'mock',
  },
  {
    platform_id: 'surplex',
    lot_id: 'SPX-MOCK-003',
    title: 'Trumpf TruLaser 1030 — Máquina de Corte Láser CO2',
    description: 'Cortadora láser Trumpf TruLaser 1030 con potencia 2.5kW, mesa 3000x1500. Incluye chiller y extractor de humos. Operativa hasta última semana.',
    category: 'Corte Láser',
    subcategory: 'Láser CO2',
    source_url: 'https://www.surplex.com/es/l/trumpf-trulaser-1030.html',
    current_bid: 35000,
    currency: 'EUR',
    estimated_resale: 75000,
    buyer_premium_pct: 16,
    has_reserve: true,
    starting_bid: 28000,
    city: 'Milán',
    region: 'Lombardía',
    country: 'Italia',
    country_code: 'IT',
    lat: 45.4642,
    lng: 9.1900,
    site_type: 'factory',
    auction_end: new Date(Date.now() + 7 * 86400000).toISOString(),
    inspection_available: true,
    make: 'Trumpf',
    model: 'TruLaser 1030',
    year: 2016,
    condition: 'good' as const,
    hours: 18000,
    weight_kg: 8500,
    source: 'mock',
  },
  {
    platform_id: 'maynards',
    lot_id: 'MAY-MOCK-004',
    title: 'Lincoln Electric S350 — Fuente de Soldadura Multiproceso',
    description: 'Fuente de soldadura Lincoln Electric S350 multiproceso MIG/TIG/Stick. Poco uso, incluye carrete de hilo y antorcha.',
    category: 'Neumática y Compresores',
    subcategory: 'Soldadura',
    source_url: 'https://www.maynards.com/l/lincoln-electric-s350.html',
    current_bid: 2800,
    currency: 'EUR',
    estimated_resale: 6500,
    buyer_premium_pct: 15,
    has_reserve: false,
    starting_bid: 2000,
    city: 'Toronto',
    region: 'Ontario',
    country: 'Canadá',
    country_code: 'CA',
    lat: 43.6532,
    lng: -79.3832,
    site_type: 'warehouse',
    auction_end: new Date(Date.now() + 2 * 86400000).toISOString(),
    inspection_available: false,
    make: 'Lincoln Electric',
    model: 'S350',
    year: 2019,
    condition: 'good' as const,
    hours: 1200,
    source: 'mock',
  },
  {
    platform_id: 'troostwijk',
    lot_id: 'TWK-MOCK-005',
    title: 'Jungheinrich ETV 216 — Reach Truck 1.6T',
    description: 'Reach truck Jungheinrich ETV 216, capacidad 1600kg, altura elevación 7.5m. Batería litio 48V incluida. Mantenimiento al día.',
    category: 'Logística y Almacén',
    subcategory: 'Carretillas Reach',
    source_url: 'https://www.troostwijkauctions.com/es/l/jungheinrich-etv-216.html',
    current_bid: 8200,
    currency: 'EUR',
    estimated_resale: 18000,
    buyer_premium_pct: 18,
    has_reserve: false,
    starting_bid: 6000,
    city: 'Ámsterdam',
    region: 'Holanda Septentrional',
    country: 'Países Bajos',
    country_code: 'NL',
    lat: 52.3676,
    lng: 4.9041,
    site_type: 'warehouse',
    auction_end: new Date(Date.now() + 4 * 86400000).toISOString(),
    inspection_available: true,
    make: 'Jungheinrich',
    model: 'ETV 216',
    year: 2021,
    condition: 'excellent' as const,
    hours: 2100,
    weight_kg: 3200,
    source: 'mock',
  },
  {
    platform_id: 'surplex',
    lot_id: 'SPX-MOCK-006',
    title: 'Amada HFE 2204 — Plegadora Hidráulica 4 Ejes CNC',
    description: 'Plegadora hidráulica Amada HFE 2204, 220T, 4m longitud. Control CNC Fanuc. Herramentales incluidos.',
    category: 'Conformado de Chapa',
    subcategory: 'Plegadoras',
    source_url: 'https://www.surplex.com/es/l/amada-hfe-2204.html',
    current_bid: 22000,
    currency: 'EUR',
    estimated_resale: 48000,
    buyer_premium_pct: 16,
    has_reserve: true,
    starting_bid: 18000,
    city: 'Múnich',
    region: 'Baviera',
    country: 'Alemania',
    country_code: 'DE',
    lat: 48.1351,
    lng: 11.5820,
    site_type: 'factory',
    auction_end: new Date(Date.now() + 6 * 86400000).toISOString(),
    inspection_available: true,
    make: 'Amada',
    model: 'HFE 2204',
    year: 2017,
    condition: 'good' as const,
    hours: 12000,
    weight_kg: 14500,
    source: 'mock',
  },
  {
    platform_id: 'maynards',
    lot_id: 'MAY-MOCK-007',
    title: 'Atlas Copco GA 37 — Compresor de Tornillo 37kW',
    description: 'Compresor de tornillo Atlas Copco GA 37 con secador refrigeración y filtro incluidos. Funcionamiento perfecto.',
    category: 'Neumática y Compresores',
    subcategory: 'Compresores',
    source_url: 'https://www.maynards.com/l/atlas-copco-ga-37.html',
    current_bid: 4500,
    currency: 'EUR',
    estimated_resale: 11000,
    buyer_premium_pct: 15,
    has_reserve: false,
    starting_bid: 3000,
    city: 'Detroit',
    region: 'Michigan',
    country: 'EE.UU.',
    country_code: 'US',
    lat: 42.3314,
    lng: -83.0458,
    site_type: 'factory',
    auction_end: new Date(Date.now() + 1 * 86400000).toISOString(),
    inspection_available: true,
    make: 'Atlas Copco',
    model: 'GA 37',
    year: 2019,
    condition: 'good' as const,
    hours: 8500,
    weight_kg: 680,
    source: 'mock',
  },
  {
    platform_id: 'troostwijk',
    lot_id: 'TWK-MOCK-008',
    title: 'ABB IRB 6700-235/2.65 — Robot de Soldadura',
    description: 'Robot ABB IRB 6700 con controlador OmniCore y software RobotWare. Capacidad 235kg, alcance 2.65m. Desmantelación de planta completa.',
    category: 'Robótica Industrial',
    subcategory: 'Robots de Soldadura',
    source_url: 'https://www.troostwijkauctions.com/es/l/abb-irb-6700.html',
    current_bid: 24000,
    currency: 'EUR',
    estimated_resale: 52000,
    buyer_premium_pct: 18,
    has_reserve: true,
    starting_bid: 20000,
    city: 'Zaragoza',
    region: 'Aragón',
    country: 'España',
    country_code: 'ES',
    lat: 41.6488,
    lng: -0.8891,
    site_type: 'factory',
    auction_end: new Date(Date.now() + 8 * 86400000).toISOString(),
    inspection_available: true,
    make: 'ABB',
    model: 'IRB 6700-235/2.65',
    year: 2017,
    condition: 'good' as const,
    hours: 15000,
    weight_kg: 1250,
    source: 'mock',
  },
  {
    platform_id: 'surplex',
    lot_id: 'SPX-MOCK-009',
    title: 'Arburg Allrounder 470 S — Inyectora de Plástico 150T',
    description: 'Máquina inyectora Arburg Allrounder 470S con unidad de cierre 150T. Incluye molde para tapas. Cierre de producción.',
    category: 'Plástico y Caucho',
    subcategory: 'Inyectoras',
    source_url: 'https://www.surplex.com/es/l/arburg-allrounder-470s.html',
    current_bid: 12000,
    currency: 'EUR',
    estimated_resale: 28000,
    buyer_premium_pct: 16,
    has_reserve: false,
    starting_bid: 9000,
    city: 'Lyon',
    region: 'Ródano-Alpes',
    country: 'Francia',
    country_code: 'FR',
    lat: 45.7640,
    lng: 4.8357,
    site_type: 'factory',
    auction_end: new Date(Date.now() + 10 * 86400000).toISOString(),
    inspection_available: true,
    make: 'Arburg',
    model: 'Allrounder 470 S',
    year: 2015,
    condition: 'fair' as const,
    hours: 22000,
    weight_kg: 5500,
    source: 'mock',
  },
  {
    platform_id: 'netbid',
    lot_id: 'NET-MOCK-010',
    title: 'Hans Laser MF-E-A — Marcador Láser Fibra 20W',
    description: 'Marcador láser de fibra Hans Laser MF-E-A 20W. Ideal para marcado de metales, plásticos y etiquetas. Incluye software de marcado.',
    category: 'Corte Láser',
    subcategory: 'Marcado Láser',
    source_url: 'https://www.netbid.com/l/hans-laser-mf-e-a.html',
    current_bid: 1800,
    currency: 'EUR',
    estimated_resale: 4500,
    buyer_premium_pct: 14,
    has_reserve: false,
    starting_bid: 1200,
    city: 'Berlín',
    region: 'Berlín',
    country: 'Alemania',
    country_code: 'DE',
    lat: 52.5200,
    lng: 13.4050,
    site_type: 'workshop',
    auction_end: new Date(Date.now() + 9 * 86400000).toISOString(),
    inspection_available: false,
    make: 'Hans Laser',
    model: 'MF-E-A',
    year: 2022,
    condition: 'excellent' as const,
    hours: 800,
    weight_kg: 45,
    source: 'mock',
  },
];

async function seedMockData() {
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  console.log(`Seeding ${MOCK_ASSETS.length} mock assets...`);

  for (const asset of MOCK_ASSETS) {
    // Calculate KPIs
    const buyerPremium = asset.current_bid * (asset.buyer_premium_pct / 100);
    const transport = 1500;
    const taxes = (asset.current_bid + buyerPremium) * 0.21;
    const refurbishment = asset.current_bid * 0.05;
    const totalAcquisitionCost = asset.current_bid + buyerPremium + transport + taxes + refurbishment;
    const estimatedResaleValue = asset.estimated_resale;
    const grossProfit = estimatedResaleValue - totalAcquisitionCost;
    const roi = totalAcquisitionCost > 0 ? grossProfit / totalAcquisitionCost : 0;
    const netProfitMargin = estimatedResaleValue > 0 ? grossProfit / estimatedResaleValue : 0;
    const paybackMonths = grossProfit > 0 ? Math.ceil(totalAcquisitionCost / (grossProfit / 6)) : 999;
    const tir = roi > 0 ? roi / 2 : 0;
    const arbitrageScore = roi > 0.5 ? 95 : roi > 0.3 ? 75 : roi > 0.1 ? 55 : 35;
    const isGanga = roi > 0.4;
    const riskScore = asset.condition === 'excellent' ? 15 : asset.condition === 'good' ? 30 : asset.condition === 'fair' ? 55 : 80;

    const { error } = await supabase.from('auctions').upsert({
      platform_id: asset.platform_id,
      lot_id: asset.lot_id,
      title: asset.title,
      description: asset.description,
      category: asset.category,
      subcategory: asset.subcategory,
      source_url: asset.source_url,
      source: 'mock',
      current_bid: asset.current_bid,
      currency: asset.currency,
      estimated_resale: asset.estimated_resale,
      buyer_premium_pct: asset.buyer_premium_pct,
      has_reserve: asset.has_reserve,
      starting_bid: asset.starting_bid,
      city: asset.city,
      region: asset.region,
      country: asset.country,
      country_code: asset.country_code,
      lat: asset.lat,
      lng: asset.lng,
      site_type: asset.site_type,
      auction_end: asset.auction_end,
      inspection_available: asset.inspection_available,
      make: asset.make,
      model: asset.model,
      year: asset.year,
      condition: asset.condition,
      hours: asset.hours,
      weight_kg: asset.weight_kg,
      total_acquisition_cost: totalAcquisitionCost,
      buyer_premium: buyerPremium,
      taxes: taxes,
      transport: transport,
      refurbishment: refurbishment,
      estimated_resale_value: estimatedResaleValue,
      gross_profit: grossProfit,
      roi: roi,
      net_profit_margin: netProfitMargin,
      payback_months: paybackMonths,
      tir: tir,
      arbitrage_score: arbitrageScore,
      is_ganga: isGanga,
      risk_score: riskScore,
      risk_level: riskScore < 25 ? 'low' : riskScore < 50 ? 'medium' : 'high',
      is_active: true,
    }, { onConflict: 'platform_id,lot_id' });

    if (error) {
      console.error(`Error inserting ${asset.lot_id}:`, error.message);
    } else {
      console.log(`✓ ${asset.lot_id}: ${asset.title}`);
    }
  }

  console.log('Done seeding mock data.');
}

seedMockData();